# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy all files
COPY . .

# Install dependencies without running prepare scripts
RUN npm install --production --ignore-scripts

# Make entrypoints executable
RUN chmod +x bin/task-master.js mcp-server/server.js

# Default command
CMD ["node", "mcp-server/server.js"]
